
# The URL the site will be built for
base_url = "ileduboutdumonde.xyz"

title = "Ile du Bout du Monde"
description = "Un hivernage sur l'Île d'Amsterdam"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "en"

highlight_theme = "solarized-dark"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true
smart_punctuation = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100


[extra]
# Put all your custom variables here

site_menus = [
  { url = "http://127.0.0.1:1111/", name = "Accueil" },
  { url = "http://127.0.0.1:1111/about", name = "À propos" },
  { url = "http://127.0.0.1:1111/icos/", name = "Parlons science" },
  { url = "http://127.0.0.1:1111/starting/", name = "Préparatifs" },
  { url = "http://127.0.0.1:1111/mdf/", name = "À bord du Marion" },
  { url = "http://127.0.0.1:1111/base/", name = "Vie en station" },
  { url = "http://127.0.0.1:1111/people/", name = "Portraits" },
  { url = "http://127.0.0.1:1111/galerie", name = "Galerie" },
  { url = "http://127.0.0.1:1111/lexique", name = "Lexique taafien" },
  { url = "http://127.0.0.1:1111/contact", name = "Me contacter" },
]

